source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'

#Internacinalizacao do rails
gem 'rails-i18n'

#Manage Procfile-based application
gem 'foreman'

#Flexible authentication solution for Rails with Warden
gem 'devise'

#Translation for the devise gem
gem 'devise-i18n'

#Enum translation
gem 'enum_help'

#Minimal authorization through OO design and pure Ruby classes
gem "pundit"

#Integration of RubyMoney
gem 'money-rails'

#Easy file attachment management for ActiveRecord
gem "paperclip", "~> 6.0.0"

#Rails gem of the Bootstrap based admin theme SB Admin 2. 
gem 'bootstrap_sb_admin_base_v2'

# jQuery UI for the Rails asset pipeline
gem 'jquery-ui-rails'

#Markdown
gem 'redcarpet'

#FriendlyId is the “Swiss Army bulldozer” of slugging and permalink plugins for ActiveRecord. 
gem 'friendly_id', '~> 5.2.1'

#Wiselinks
gem 'wiselinks'

#A Scope & Engine based, clean, powerful, customizable and sophisticated paginator for Ruby webapps
gem 'kaminari'

#Kaminari i18n
gem 'kaminari-i18n'

#A Ruby Gem that wraps the functionality of jQuery Raty library, and provides optional IMDB style rating.
gem 'ratyrate'

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap', '3.3.7'

  gem 'rails-assets-notifyjs', '0.4.2'

  #Bootstrap notify
  gem 'rails-assets-bootstrap.growl'

  #Animate css
  gem 'rails-assets-animate-css'
  #A better javascript box  
  gem 'rails-assets-bootbox'
  #Bootstrap markdown
  gem 'rails-assets-bootstrap-markdown'
  #Marked to preview the markdown
  gem 'rails-assets-marked'

end

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  #Gem de customizacao para os erros
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'

  #Gerar diagramas de relacionamento ( instalar o graphviz antes)
	gem 'rails-erd'

  #A library for generating fake data such as names, addresses, and phone numbers.
  gem 'faker'

  #Markdown Lorem Ipsum generator
  gem 'doctor_ipsum'
  
  #Envio de email
  gem 'mailcatcher'

  gem 'lerolero_generator'
end

